blog/article/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = "article"

urlpatterns = [
    path('', dashboard, name = "dashboard"),
    # path('dashboard/', dashboard, name = "dashboard"),
    # path('addarticle/', addarticle, name = "addarticle"),
    path('detail/<int:id>', detail, name = "detail"),
    # path('update/<int:id>', updateArticle, name = "updateArticle"),
    # path('delete/<int:id>', deleteArticle, name = "deleteArticle"),
    # path('comment/<int:id>', comment, name = "comment"),

    # path('<slug:slug>/', allpost, name = "allpost"),
    # path('<int:id>/', allpost, name = "allpost"),
    # url(r'^(?P<slug>.*)/$', allpost, name = "allpost"),

    # path('category-dashboard/', categorydashboard, name = "categorydashboard"),
    # path('add-category-article/', addcategoryArticle, name = "addcategoryArticle"),
    # path('category-detail/<int:id>', categorydetail, name = "categorydetail"),
    # path('category-update/<int:id>', updateCategoryArticle, name = "updateCategoryArticle"),
    # path('category-delete/<int:id>', deleteCategoryArticle, name = "deleteCategoryArticle"),
    # path('category/<int:id>', category,name="category")

]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
# Following two modules for File Upload operations
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from product import views as prod
from article import views


urlpatterns = [
    path('', views.post, name="post"),
    path('admin/',admin.site.urls),
    # path('admin/', views.index, name = "index"),
    # path('about', views.about, name = "about"),
    path('articles/',include('article.urls')),
    # path('user/',include('user.urls')),
    path('products/',include('product.urls')),
    path('ckdeditor/',include('ckeditor_uploader.urls')),
    path('contact/', views.contact, name = "contact"),
    url(r'^post/(?P<slug>.*)/$', views.allpost, name = "allpost"),
    url(r'^product/(?P<slug>.*)/$', prod.allProduct, name = "allProduct"),
    path('category-article/<int:id>/', views.get_category, name = "get_category_article"),
    path('category-product/<int:id>/', prod.get_category, name = "get_category_product"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf.urls import url

app_name = "product"

urlpatterns = [
    path('', dashboard, name = "dashboard"),
    # path('item/<int:id>',allProduct, name="allProduct"),
    # path('addproduct/', products, name = "addproduct"),
    path('detail-product/<int:id>', detail, name = "detail"),
    # path('update/<int:id>', updateProduct, name = "updateProduct"),
    # path('delete/<int:id>', deleteProduct, name = "deleteProduct"),

    # path('category-dashboard/', categorydashboard, name = "categorydashboard"),
    # path('add-category-product/', addcategoryProduct, name = "addcategoryProduct"),
    # path('category-update/<int:id>', updateCategoryProduct, name = "updateCategoryProduct"),
    # path('category-delete/<int:id>', deleteCategoryProduct, name = "deleteCategoryProduct"),
    
    # path('contact-dashboard/',dashboardContact,name="dashboardContact"),
    # path('contact-delete/<int:id>', deleteContact, name = "deleteContact"),
]

blog/templates/banner.html
{% load static %}
<div class="banner">
    <ul class="slidebanner">
        {% for slide in slide_show %}
        <li>
            <div class="img-sl">
                <img src="{{slide.image.url}}" alt="">
            </div>
            <div class="txt-slbn">
            {% if slide.content1 %}
                <h2>
                    <a href="#">{{slide.content1}}</a>
                </h2>
            {% endif %}
            {% if slide.content2%}
                <h3>{{slide.content2}}</h3>
            {% endif %}
            {% if slide.link%}
                <a href="{{slide.link}}" class="seemore-bn">Xem chi tiết</a>
            {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Viện thiết kế tàu quân sự</title>
    <link rel="stylesheet" href="{% static 'css/index/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightgallery.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightslider.min.css' %}">
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}"> {% endcomment %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
</head>

<body>
    <header>
        {% block header_menu %}
        
        {% endblock header_menu %}
        {% block header_banner %}

        {% endblock header_banner %}
    </header>
    <div id="_jafban"></div>
    {% block body %}

    {% endblock body %}

    <footer>
        <div class="footer">
            <div class="container">
                <div class="footer-ct">
                    <div class="it-ft1">
                        <h3><a href="#">thông tin liên hệ</a></h3>
                        <ul>
                            <li><i class="fa fa-map-marker" aria-hidden="true"></i><a href="#">Đường Ỷ Lan , Xã Dương Xá , Huyện Gia Lâm , TP. Hà Nội</a></li>
                            <li><i class="fa fa-phone" aria-hidden="true"></i><a href="#">02439.336.234</a></li>
                            <li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="#">+84 2439.336.234</a></li>
                            <li><i class="fa fa-globe" aria-hidden="true"></i><a href="#">vienthietketauquansu</a></li>
                        </ul>
                    </div>
                    <div class="it-ft1">
                        <h3><a href="#">Liên kết</a></h3>
                        <ul>
                            <li><a href="#">Trang chủ</a></li>
                            <li><a href="#">Giới thiệu</a></li>
                            <li><a href="#">Sản phẩm</a></li>
                            <li><a href="#">Tin tức</a></li>
                            <li><a href="#">Liên hệ</a></li>
                        </ul>
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="it-ft1">
                        <h3><a href="#">đăng kí</a></h3>
                        <p>Đăng kí nhận thông tin sản phẩm, báo giá</p>
                        <form action="">
                            <div class="form-ft">
                                <input type="text" placeholder="Tìm kiếm...">
                                <button><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/index/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/lightgallery.js' %}"></script>
    <script src="{% static 'js/lightslider.min.js' %}"></script>
    <script src="{% static 'js/slidegalarey.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/swiper.min.js' %}"></script> {% endcomment %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

blog/templates/category_article.html

{% extends 'base.html' %}
{% load static %}
{% block header_menu %}
    {% include 'header_without_banner.html' %}
{% endblock header_menu %}
{% comment %} {% block header_banner %}
    <div class="banner-mn">
        <div class="content-bn">
            <div class="_jctbn">
            </div>
        </div>
    </div>
{% endblock header_banner %} {% endcomment %}

{% block body %}
<div id="lst-news"></div>

    <section>
        <div class="mt-item" style="margin-top: 15px;">
            <div class="container">
                <div class="mtiem-ct">
                    <div class="listitlt">
                    {% for category in categories %}
                    {% if category.id == 15 %}
                        <div class="itlthis">
                            <div class="img-itlt">
                                <a href="{% url 'get_category_article' '15' %}"><img src="{{category.image_url|default_if_none:'#'}}" alt=""></a>
                            </div>
                            <div class="txt-itlt">
                                <a href="{% url 'get_category_article' '15' %}"><h4>{{category.title}}</h4></a>
                            </div>
                        </div>
                    {% else %}
                        <div class="itlthis">
                            <div class="img-itlt">
                                <a href="{% url 'allpost' category.slug %}"><img src="{{category.image_url|default_if_none:'#'}}" alt=""></a>
                            </div>
                            <div class="txt-itlt">
                                <a href="{% url 'allpost' category.slug %}"><h4>{{category.title}}</h4></a>
                            </div>
                        </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% comment %} <div class="seemore-n">
                    <a href="#">xem thêm</a>
                </div> {% endcomment %}
                    <div class="seemore-n">
                        {% comment %} <a href="#">xem thêm</a> {% endcomment %}
                        <div class="pagination">
                            {% if categories.has_previous %}
                                <a class="pagination-action" href="?page=1">
                                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                                </a>
                                <a class="pagination-action" href="?page={{ categories.previous_page_number }}">
                                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                            <span class="pagination-current">{{ categories.number }}</span>
                            <span class="pagination-of">của</span>
                            <span class="pagination-total">{{ categories.paginator.num_pages }}</span>
                            {% if categories.has_next %}
                                <a class="pagination-action" href="?page={{ categories.next_page_number }}">
                                    <i class="fa fa-angle-right" aria-hidden="true"></i> </a>
                                <a class="pagination-action" href="?page={{ categories.paginator.num_pages }}">
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock body%}

blog/templates/category_product.html

{% extends 'base.html' %}
{% load static %}
{% block header_menu %}
    {% include 'header_without_banner.html' %}
{% endblock header_menu %}
{% comment %} {% block header_banner %}
    <div class="banner-mn">
        <div class="content-bn">
            <div class="_jctbn">
            </div>
        </div>
    </div>
{% endblock header_banner %} {% endcomment %}

{% block body %}
<div id="lst-news"></div>

    <section>
        <div class="mt-item" style="margin-top: 15px;">
            <div class="container">
                <div class="mtiem-ct">
                    <div class="listitlt">
                    {% for category in categories %}
                        <div class="itlthis">
                            <div class="img-itlt">
                                <a href="{% url 'allProduct' category.slug %}"><img src="{{category.image_url|default_if_none:'#'}}" alt=""></a>
                            </div>
                            <div class="txt-itlt">
                                <a href="{% url 'allProduct' category.slug %}"><h4>{{category.title}}</h4></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% comment %} <div class="seemore-n">
                    <a href="#">xem thêm</a>
                </div> {% endcomment %}
                    <div class="seemore-n">
                        {% comment %} <a href="#">xem thêm</a> {% endcomment %}
                        <div class="pagination">
                            {% if categories.has_previous %}
                                <a class="pagination-action" href="?page=1">
                                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                                </a>
                                <a class="pagination-action" href="?page={{ categories.previous_page_number }}">
                                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                            <span class="pagination-current">{{ categories.number }}</span>
                            <span class="pagination-of">của</span>
                            <span class="pagination-total">{{ categories.paginator.num_pages }}</span>
                            {% if categories.has_next %}
                                <a class="pagination-action" href="?page={{ categories.next_page_number }}">
                                    <i class="fa fa-angle-right" aria-hidden="true"></i> </a>
                                <a class="pagination-action" href="?page={{ categories.paginator.num_pages }}">
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock body%}

blog/templates/item.html

{% extends 'base.html' %}
{% load static %}
{% block header_menu %}
    {% include 'header_without_banner.html' %}
{% endblock header_menu %}
{% comment %} {% block header_banner %}
    <div class="banner-mn">
        <div class="content-bn">
            <div class="_jctbn">
            </div>
        </div>
    </div>
{% endblock header_banner %} {% endcomment %}

{% block body %}
<div id="lst-news"></div>

    <section>
        <div class="mt-item" style="margin-top: 15px;">
            <div class="container">
                <div class="mtiem-ct">
                    <div class="listitlt">
                    {% for product in products %}
                        <div class="itlthis">
                        <div class="img-itlt">
                            <a href="{% url 'product:detail' product.id %}"><img src="{{product.image_url|default_if_none:'#'}}" alt=""></a>
                        </div>
                        <div class="txt-itlt">
                            <h4 title="{{product.title}}">{{product.title|truncatechars:55}}</h4>
                            <span class="_wrOr">Mã SP: {{product.code}}</span>
                            {% comment %} <a href="javascript:" class="_wrRe">Liên hệ</a> {% endcomment %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% comment %} <div class="seemore-n">
                    <a href="#">xem thêm</a>
                </div> {% endcomment %}
                    <div class="seemore-n">
                        {% comment %} <a href="#">xem thêm</a> {% endcomment %}
                        <div class="pagination">
                            {% if products.has_previous %}
                                <a class="pagination-action" href="?page=1">
                                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                                </a>
                                <a class="pagination-action" href="?page={{ products.previous_page_number }}">
                                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                            <span class="pagination-current">{{ products.number }}</span>
                            <span class="pagination-of">của</span>
                            <span class="pagination-total">{{ products.paginator.num_pages }}</span>
                            {% if products.has_next %}
                                <a class="pagination-action" href="?page={{ products.next_page_number }}">
                                    <i class="fa fa-angle-right" aria-hidden="true"></i> </a>
                                <a class="pagination-action" href="?page={{ products.paginator.num_pages }}">
                                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="popup-form">
        <div class="formpu">
            <h2>Liên Hệ</h2>
            <div>
                <form enctype="multipart/form-data" method = "POST">{% csrf_token %}
                {{form.as_p}}
                {% comment %} {{form|crispy}} {% endcomment %}
                <button href="" type="submit" class = "btn btn-danger">Gửi Liên hệ</button>
            </form>
            </div>
            <div class="btclose">
                <i class="fa fa-times" aria-hidden="true"></i>
            </div>
        </div>
        <div class="bg-close"></div>
    </div>
{% endblock body%}

blog/templates/item_detail.html

{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block header_menu %}
    {% include 'header_without_banner.html' %}
{% endblock header_menu %}
{% comment %} {% block header_banner %}
    <div class="banner-mn">
        <div class="content-bn">
            <div class="_jctbn">
            </div>
        </div>
    </div>
{% endblock header_banner %} {% endcomment %}
{% block body %}
    {% if products %}
    <section>
        <div class="dt-item">
            <div class="container">
                <div class="dt-itct">
                    <div class="sliderleft">
                        <ul id="imageGallery">
                            <li data-thumb="{{products.image_url|default_if_none:'#'}}">
                                <img src="{{products.image_url|default_if_none:'#'}}" />
                            </li>
                            {% for photo in photos%}
                            <li data-thumb="{{photo.image.url}}">
                                <img src="{{photo.image.url}}" />
                            </li>
                            {% endfor %}
                        </ul>
                        <div class="actglr">
                            <a href="javascript:" class="prevglr"><i class="fa fa-angle-left"></i></a>
                            <a href="javascript:" class="nextglr"><i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                    <div class="right-tb">
                        <p class="iditem">Mã sản phẩm: <span>{{products.code}}</span></p>
                        <p class="nmtable">thông số cơ bản</p>
                        <div class="table-item">
                            <table>
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Thông số</th>
                                        <th>Đơn vị</th>
                                        <th>giá trị</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for prod_type in prod_type_list%}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td class="text-left">{{prod_type.name}}</td>
                                        <td>{{prod_type.unit}}</td>
                                        <td>{{prod_type.value}}</td>
                                    </tr>
                                {% endfor %}
                                    {% comment %} <tr>
                                        <td>2</td>
                                        <td>Chiều rộng/ Breath</td>
                                        <td>m</td>
                                        <td>{{products.breath}}</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Chiều cao mạn/ Depth</td>
                                        <td>m</td>
                                        <td>{{products.depth}}</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>Chiều chìm/ Draught:</td>
                                        <td>m</td>
                                        <td>{{products.draught}}</td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>Lượng chiếm nước đầy tải/ Full load Displacement:</td>
                                        <td>t</td>
                                        <td>{{products.fullLoad}}</td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>Thuyền viên/cán bộ/ Nos of crews and officers:</td>
                                        <td>người(ppl)</td>
                                        <td>{{products.crews}}</td>
                                    </tr>
                                    <tr>
                                        <td>7</td>
                                        <td>Vận tốc lớn nhất/ Max speed:</td>
                                        <td>hải lý/giờ(knots)</td>
                                        <td>{{products.maxDrag}}</td>
                                    </tr> {% endcomment %}
                                </tbody>
                            </table>
                        </div>
                        <div class="bt-rdtb">
                            {% comment %} <a href="javascript:">Liên hệ</a> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div id="mtitem"></div>
    <section>
        <div class="mt-item">
            <div class="container">
                <div class="mtiem-ct">
                    <h2 class="titmtitem">Mô tả Sản Phẩm</h2>
                    <p>{{products.content|safe}}</p>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <div id="mtitem"></div>
    {% if all_products %}
    <section>
        <div class="mt-item">
            <div class="container">
                <div class="mtiem-ct">
                    <h3>sản phẩm tương tự</h3>
                    <div class="listitlt">
                    {% for all_product in all_products%}
                        <div class="itlthis">
                        <div class="img-itlt">
                            <a href="{% url 'product:detail' all_product.id %}"><img src="{{all_product.image_url|default_if_none:'#'}}" alt=""></a>
                        </div>
                        <div class="txt-itlt">
                            <h4 title="{{all_product.title}}">{{all_product.title|truncatechars:55}}</h4>
                            <span class="_wrOr">Mã SP: {{all_product.code}}</span>
                            {% comment %} <a href="javascript:" class="_wrRe">Liên hệ</a> {% endcomment %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% comment %} <div class="seemore-n">
                    <a href="#">xem thêm</a>
                </div> {% endcomment %}
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <div class="popup-form">
        <div class="formpu">
            <h2>Liên Hệ</h2>
            <div>
                <form enctype="multipart/form-data" method = "POST">{% csrf_token %}
                {{form.as_p}}
                {% comment %} {{form|crispy}} {% endcomment %}
                <button href="" type="submit" class = "btn btn-danger">Gửi Liên hệ</button>
            </form>
            </div>
            {% comment %} <form action="">
                <div class="form-group">
                    <input type="text" placeholder="Họ và tên" name="">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Điện Thoại" name="">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Email" name="">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Địa chỉ" name="">
                </div>
                <div class="form-group">
                    <textarea name="" placeholder="Ghi chú"></textarea>
                </div>
                <button>Gửi liên hệ</button>
            </form> {% endcomment %}
            <div class="btclose">
                <i class="fa fa-times" aria-hidden="true"></i>
            </div>
        </div>
        <div class="bg-close"></div>
    </div>
{% endblock body %}

blog/templates/post_detail.html

{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block header_menu %}
    {% include 'header_without_banner.html' %}
{% endblock header_menu %}
{% comment %} {% block header_banner %}
    <div class="banner-mn">
        <div class="content-bn">
            <div class="_jctbn">
            </div>
        </div>
    </div>
{% endblock header_banner %} {% endcomment %}
{% block body %}
<div id="post"></div>
    {% if article %}
    <section>
        <div class="post-txt">
            <div class="container">
                <div class="pstxt-ct">
                    <div class="txt-lft">
                        <h1>{{article.title}}</h1>
                        <span class="time-bv"><i class="fa fa-clock-o" aria-hidden="true"></i>{{article.created_date|date:"d M Y"}}</span>
                        <p>{{article.content|safe}}<p>
                    </div>
                    <div class="txt-rght">
                        <h2>Mới nhất</h2>
                        <ul>
                        {% for articles in article_list%}
                            <li>
                                <span class="time-bv"><i class="fa fa-clock-o" aria-hidden="true"></i>{{articles.created_date|date:"D d M Y"}}</span>
                                <a href="{% url 'article:detail' articles.id %}" title="{{articles.title}}">{{articles.title|truncatechars:65}}</a>
                            </li>
                        {% endfor %}
                                {% comment %} <li>
                                    <span class="time-bv"><i class="fa fa-clock-o" aria-hidden="true"></i>03/6/2020</span>
                                    <a href="#">day la bai viet khac</a></li>
                                    <li>
                                        <span class="time-bv"><i class="fa fa-clock-o" aria-hidden="true"></i>03/6/2020</span>
                                        <a href="#">day la bai viet khac</a></li>
                                        <li>
                                            <span class="time-bv"><i class="fa fa-clock-o" aria-hidden="true"></i>03/6/2020</span>
                                            <a href="#">day la bai viet khac</a></li> {% endcomment %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
{% endblock body %}